# This is a basic workflow to help you get started with Actions

name: JpetStore

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
   # branches: [ master ]
  #pull_request:
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting.
          fetch-depth: 0
      
        
      # Container check
      - name: Check the container 
        run: echo this is personal server
      
      # Git Pull
      - name: Git Pull 
        run: |
          git clone https://github.com/Nish-1992/JPetStore_demo.git
          pwd
       
      # SonarQube Analysis 
      
      - name: Perform SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
          #projectKey: "SSC-service-product-web-app"
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
